CREATE TABLE "dim_clientes" (
  "id_cliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "ciudad" varchar(50),
  "segmento" varchar(30)
);

CREATE TABLE "dim_fecha" (
  "id_fecha" integer PRIMARY KEY,
  "fecha" date,
  "anio" integer,
  "mes" integer,
  "dia" integer,
  "dia_semana" varchar(20)
);

CREATE TABLE "dim_mesero" (
  "id_mesero" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "turno" varchar(50) NOT NULL,
  "anios_experiencia" decimal(10,2)
);

CREATE TABLE "dim_productos" (
  "id_producto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "categoria" varchar(50),
  "precio_unitario" decimal(10,2)
);

CREATE TABLE "fact_ventas" (
  "id_venta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" integer,
  "id_cliente" integer,
  "id_fecha" integer,
  "cantidad" integer,
  "ventas" decimal(10,2),
  "costo" decimal(10,2),
  "id_mesero" integer
);

ALTER TABLE "fact_ventas" ADD FOREIGN KEY ("id_producto") REFERENCES "dim_productos" ("id_producto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fact_ventas" ADD FOREIGN KEY ("id_cliente") REFERENCES "dim_clientes" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fact_ventas" ADD FOREIGN KEY ("id_fecha") REFERENCES "dim_fecha" ("id_fecha") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fact_ventas" ADD FOREIGN KEY ("id_mesero") REFERENCES "dim_mesero" ("id_mesero") DEFERRABLE INITIALLY IMMEDIATE;
